version: '3'

services:
  pangeia-collector:
    container_name: pangeia-collector
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '9090:9090'
    volumes:
      - ./:/usr/src/app/

    networks:
      - bifrost

# docker network create --driver bridge bifrost
networks:
  bifrost:
    external: true
